FROM python:3.12.8-slim-bullseye

WORKDIR /

COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY app /app

ENTRYPOINT ["/bin/bash", "-c", "/bin/bash"]
# CMD ["fastapi", "run", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]
